### PR TITLE
A:currentgk.in

### PR DESCRIPTION
**Pull request by mediumkreation**
**Found in URL**: https://currentgk.in/best-gk-books/
currentgk in_19-03-09 22:36:56
currentgk in_19-02-18 23:40:56
currentgk in_19-02-18 23:31:23

### CODE REVIEW

**Comment by monzta** [comment]
Aren't these books somehow the point of this page? I mean there is a button on the top to this page and when a user clicks on it, (s)he will land on a broken page.

**Comment by mediumkreation** [comment]
agreed, In first looks it seems to be a section of the site.
I am not sure, dose that make it eligible to post ads, or referral links ?

**Comment by monzta** [comment]
I think in this case it shouldn't be removed.

**Comment by mediumkreation** [comment]
ok updated

**Pull request merged**
