### PR TITLE
A:manithan.com

### PR DESCRIPTION
**Pull request by mediumkreation**
**Found in URL**: https://www.manithan.com/india/04/193084?
manithan com_18-10-31 22 17 15
manithan com_18-10-31 23 56 05
manithan com_18-10-31 23 55 53
manithan com_18-10-31 23 55 44

### CODE REVIEW

**Comment by monzta** [comment]
What is the reason for blocking parsely.com and the cloudfront.net stuff which seems to be their scripts? They don't seem to be an adserver.

**Comment by mediumkreation** [comment]
> What is the reason for blocking parsely.com and the cloudfront.net stuff which seems to be their scripts? They don't seem to be an adserver.

these two sites seems to be helping in serving and injecting dynamic ads through scripts. specifically "parsely.com". 
"cloudfront.net" is an known publisher for serving Ads.

**Comment by monzta** [comment]
Could you explain how it helps? Maybe with screenshots? 

CloudFront is a known CDN for all kinds of content: https://en.wikipedia.org/wiki/Amazon_CloudFront

**Comment by mediumkreation** [comment]
Firstly responding to parsely..

the script at the end of file (related to parsely)... calls functions **recommendations()** 
which alters the DOM and pushes the Ads, I found it relevant and so blocked it. this helped me to reduce the Ad Injection, though some times it also do not help, and sometimes it even replaces and clears the content. We can have some deep dive in. 
you have mentioned the uses of  $csp in your comments, but , I am not sure how to use it :( 

below is the extracted code...
```
if(frmpage=='view' &&  typeof sharecounturl != 'undefined') {

var baseUrl = "https://api.parsely.com/v2";
var params,UUID;
var URL = sharecounturl;
var SITENAME = sname+".com";

$( document ).ready(function() {

PARSELY = {"onload": handleParselyOnLoad};
});

function handleParselyOnLoad() {

UUID = PARSELY.config.parsely_site_uuid;

if(UUID){
  params = {apikey: SITENAME ,days:2,limit: 6,uuid: UUID};

  var profileParams = 
  {
  apikey : SITENAME,
  uuid : UUID,
  url : URL
  };

var apiUrl = baseUrl + "/profile" + "?" + $.param(profileParams);
var url = apiUrl + "&callback=?";

$.getJSON(url, function(data){
        recommendations();
  });
}
else
{
  params = {apikey: SITENAME,url: URL,days: 2,limit: 3,strategy:"recency",sort:"score"};
      recommendations();
  }
};

function recommendations() {
  var recDiv = $("#recommendations");
  callback = function(data) {
  if (data != undefined) { 
    var t=data.data.length-1;
    var r1=Math.floor(Math.random() * ((2-1)+1) + 1);
    var r2=Math.floor(Math.random() * ((5-4)+1) + 4);
    var total_recommendations = 3;
    var recommendationsvalue = 0;
    $.each(data.data, function(i, datum) {
      var recindexcheckvalue = recommendationsarray.indexOf(datum.url.toString());
      if(recindexcheckvalue==-1) { 
        if(recommendationsvalue<total_recommendations) {
          var res = datum.image_url.split(".");
          var poster=res.join(".");       
          recDiv.append('<div class="recomended-item"><a href="'+(datum.url).replace('http:','')+'?ref=recommended'+(i+1)+'" class="rec-thumb"><img src="'+(poster).replace('http:','')+'" alt="'+ datum.title +'"></a><div class="rec-content"><h2><a  href="'+(datum.url).replace('http:','')+'?ref=recommended'+(i+1)+'">'+ datum.title +'</a></h2></div></div>');
          if(i==t && navigator.userAgent.match(/^[^\[]*(iPhone|iPod|BlackBerry|Android.*Mobile|BB10.*Mobile|webOS|Windows CE|IEMobile|Opera Mini|Opera Mobi|HTC|LG-|LGE|SAMSUNG|Samsung|SEC-SGH|Symbian|Nokia|PlayStation|PLAYSTATION|Nintendo DSi).*$/im)) {
             recDiv.append('<div class="recomended-item"><div id="dfp_text_view_recommended_panel" class="view-widget-box-column"><div id="dfp_text_view_recommended" ></div></div></div>');
          }  
        }
        recommendationsvalue++;
      }      
    });
    recommendationDFP();
  } else {
    console.log("no API results");
  }
  };
  // Build URL for recommendations API request

  var apiUrl = baseUrl + "/related" + "?" + $.param(params);
  var url = apiUrl + "&callback=?";
  // Update UI with URL
   $.getJSON(url, callback);
}

function replaceAll(str, find, replace) {
  return str.replace(new RegExp(find, 'g'), replace);
}


// ads replace for segmentify
function recommendationDFP(){
   var ad = {"in":"/25671928/manithan.text//view//recommended","sz":["fluid"],"sl":"dfp_text_view_recommended","pr":true,"rs":[false,0],"rf":false};
   var slot;
    slot = googletag.defineSlot(ad.in, ad.sz, ad.sl).addService(googletag.pubads()).setCollapseEmptyDiv(true, true);
    slots.push(slot);
    googletag.display(ad.sl);
  ads.push(ad);
    refreshDFP;
}

}

```

Secondly related to cloudFront..
sorry.. looks I used the wrong words to express for "cloudfront.com" ...
.. let me correct it... Its not an publisher but a CDN which is frequently used by Ad Publishers.
as we already have 100's of blocked urls(3rd level domains)  for cloudfront.

**Comment by mediumkreation** [comment]
also the same scripts are getting used for "news.lankasri.com"

**Comment by mediumkreation** [comment]
@monzta, removed block urls. as no longer required.

**Pull request merged**
