### PR TITLE
A:satyavoice.com

### PR DESCRIPTION
**Pull request by mediumkreation**
found in url:https://satyavoice.com/
satyavoice com-2022-04-11-15-49-40

### CODE REVIEW

**Comment by ghajini** [comment]
Do you consider that image as ad? hidden by `satyavoice.com###secondary .widget_media_image`

**Comment by mediumkreation** [comment]
> Do you consider that image(https://satyavoice.com/wp-content/uploads/2021/10/250x250-Middle-1-300x300.jpg) as an ad? hidden by `satyavoice.com###secondary .widget_media_image`

yes.

**Comment by ghajini** [comment]
1st party ad? i don't think its ad...do you mean your list covers political ads?

**Comment by ghajini** [comment]
> ye.. you are correct. we are covering political ads too, but its subjective.. if its govt. notice and guidelines we skip them. 

so this `https://satyavoice.com/wp-content/uploads/2021/10/250x250-Middle-1-300x300.jpg` 

is govt notice /guidelines
not an ad, if you want to hide, then that should be done in annoyance list ;not enabled by default imo

**Pull request merged**
